### ISSUE TITLE
Configuring Dynamic DNS Update with GSS-TSIG Authentication

### ISSUE THREAD

**Issue by lessfoobar** [theforeman/foreman-documentation#2137] opened 2023-03-25 18:01 UTC
in the "[Configuring DNS Zones in the IdM web UI](https://docs.theforeman.org/3.5/Installing_Server/index-katello.html#configuring-dynamic-dns-update-with-gss-tsig-authentication_foreman)" part as soon as I add the 
`grant smart-proxy/047foreman.example.com@EXAMPLE.COM wildcard * ANY;`
the zone breaks, I don't get any records resolved. Have I missconfigured something ?

**Comment by ekohl** [comment] 2023-04-07 11:04
I've moved it over to the correct repository, so it gets better visibility by the people maintaining it.

**Comment by asteflova** [comment] 2024-09-09 08:31
I was unable to reproduce this. I made it through the section linked in the report and DNS records still seem to resolve correctly. (Note that I followed the latest stable docs while this report links to version 3.5.) Still, it's hard to be sure since I don't know what exactly the failure described in the original report looked like.

The issue is reported against a procedure that is performed on the FreeIPA/Identity Management server. Just in case it helps, I'm going to link a couple of FreeIPA documentation resources on the subject:
* Configuring DNS zones: [Chapter 2. Managing DNS zones in IdM](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/working_with_dns_in_identity_management/index#managing-dns-zones-in-idm_working-with-dns-in-identity-management)
* Verifying DNS records: [1.5. Host name and DNS requirements for IdM](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/installing_identity_management/index#host-name-and-dns-requirements-for-ipa_preparing-the-system-for-ipa-server-installation)

Based on the above, I'm closing this issue. If there are any concerns, please reopen with more details about the commands you use to check the DNS records and the error messages you are seeing.

**Closed by asteflova** 2024-09-09 08:31 UTC
