### ISSUE TITLE
Build failing for 3.4 due to missing yum repos

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1552] opened 2022-08-11 10:01 UTC
Hey all!

We currently cannot build documentation for Foreman 3.4 because the yum repos are missing on yum.theforeman.org. We've had this before in the RC phase.

We can either igore broken links to `https://yum.theforeman.org/client/3.4/` or sit this one out until the repos are present.

In general, I feel like this calls for a slight reordering in the release process.

cc @upadhyeammit or someone else involved in the release process.

**Comment by maximiliankolb** [comment] 2022-08-11 10:02
See https://github.com/theforeman/foreman-documentation/runs/7784466419?check_suite_focus=true

**Comment by ekohl** [comment] 2022-08-11 11:04
We always have these kinds of issues around branching and release. It's hard to get the order exactly right.

What we typically do is:
* Create all branches
* Start the release process

IMHO the problem is that these are spread out over too long a time. It should be possible to do everything in a single day, but because we spread it over multiple people in multiple time zones things take longer than needed.

**Comment by ekohl** [comment] 2022-08-31 16:48
It has since been created. I'm going to close this for now.

**Closed by ekohl** 2022-08-31 16:48 UTC
