### ISSUE TITLE
Review menus on the navigation page

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#3321] opened 2024-09-25 17:33 UTC
Did you notice that the Katello menu has so many items already that the menu overflows and one cannot see the lowest items anyway? :D We should probably open an issue for that and try to do something about it.

_Originally posted by @Lennonka in https://github.com/theforeman/foreman-documentation/pull/3301#pullrequestreview-2328897833_

**Comment by Lennonka** [comment] 2024-09-25 18:14
The problem is that the dropdown menu doesn't scroll with the page, so users won't be able to select guides at the bottom>
![image](https://github.com/user-attachments/assets/cda863ce-c2f3-4574-8e63-5438747d8df9)

**Comment by maximiliankolb** [comment] 2024-12-05 12:56
triage: closing as duplicate of https://github.com/theforeman/foreman-documentation/issues/2752

**Closed by maximiliankolb** 2024-12-05 12:56 UTC
